### ISSUE TITLE
Generate CSV from KML

### ISSUE THREAD

**Issue by k2shah** [k2shah/wadl#44]
work around for importing KMLs directly, add method to ``Area`` class to export CSV from KML . Since KML files can hold multiple geofences, this should generate one CSV per geofence with file name found in the KML tag ``<name>`` under ``<Placemark>``. 

Should probably use a real xml parser, maybe ``lxml.etree``?

**Comment by VineetTambe** [comment]
I have added a KML to CSV parser using ``` BeautifulSoup ``` to Areas class, I tried using ``` lxml.etree ``` but it is not behaving as expected. I will work on it a little bit more and get back to you.

**Comment by k2shah** [comment]
PR is #45

**Comment by k2shah** [comment]
closed by #53
