### ISSUE TITLE
Are Self-intersecting polygons supported?

### ISSUE THREAD

**Issue by skanga** [k2shah/wadl#52]
![image](https://user-images.githubusercontent.com/1558197/106341746-3111f480-6253-11eb-91e7-133ae09f0f64.png)

Will this work if the geofences use self-intersecting polygons as shown?

**Comment by k2shah** [comment]
hi @skanga not sure actually. Can you give it a shot? the polygons are just used for checking if a grid point is inside so I think it should work?

Is there a reason you can't build a nonintersecting polygon or provide a set of polygons?
